name: Bug Report
description: Create a bug report for DCM
title: "[BUG] (fill in)"
assignees: incendial
labels:
  - "type: bug"
body:
  - type: markdown
    attributes:
      value: Thank you for filing a bug report! 🐛
  - type: textarea
    attributes:
      label: Environment and configuration
      description: |
        Please tell us about how you're running DCM.
      value: |
        DCM version:
        Dart SDK version:

        <details>
        <summary>Configuration</summary>

        ```yaml
        <!-- Paste your configuration here -->
        ```
        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you do?
      description: |
        Please include a *minimal* reproduction case. If possible, include a link to a reproduction of the problem. You can use Markdown in this field.
      value: |
        <!-- Paste the source code below: -->
        ```dart

        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: |
        You can use Markdown in this field.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What actually happened?
      description: |
        Please copy-paste the actual DCM output. You can use Markdown in this field.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false
  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important for the team to know?
