name: "Request a change (not rule-related)"
description: "Request a change that is not a bug fix, rule change, or new rule"
title: "[Change request] (fill in)"
labels:
  - "type: enhancement"
body:
  - type: input
    attributes:
      label: DCM version
      description: |
        What version of DCM are you currently using?
      placeholder: |
        e.g. v8.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What problem do you want to solve?
      description: |
        Please explain your use case in as much detail as possible.
      placeholder: |
        DCM currently...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What do you think is the correct solution?
      description: |
        Please explain how you'd like to change DCM to address the problem.
      placeholder: |
        I'd like DCM to...
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this change.
          required: false
  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important for the team to know?
