name: "New rule proposal"
description: "Propose a new rule."
title: "[New rule] (fill in)"
assignees: incendial
labels:
  - area-rules
  - "type: enhancement"
body:
  - type: markdown
    attributes:
      value: Thank you for your lint idea!
  - type: textarea
    attributes:
      label: Rule details
      description: What should the new rule do?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What type of rule is this?
      options:
        - Warns about a potential problem
        - Suggests an alternate way of doing something
        - Enforces a formatting/stylistic preference
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example code
      description: Please provide some example Dart code that this rule will warn about. This field will render as Dart.
      render: dart
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request to implement this rule.
          required: false
  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important for the team to know?
