name: Dart 2.4

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.4

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
