name: "No Response"

on:
  issue_comment:
    types:
      - created
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

jobs:
  no_response:
    runs-on: ubuntu-latest

    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          daysUntilClose: 7 # Number of days of inactivity before an issue is closed for lack of response
          responseRequiredLabel: "awaiting info" # Label requiring a response
          closeComment: >
            Without additional information, we are unfortunately not sure how to resolve this issue.
            We are therefore reluctantly going to close this issue for now. Please don't hesitate to
            comment on the issue if you have any more information for us; we will reopen it right away!
            Thanks for your contribution!
