name: "Push to BitBucket"

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ref: "master"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - run: |
          git remote add bitbucket git@bitbucket.org:DmitryKrutskikh/dart-code-metrics.git
          git config --global user.email "dmitry.krutskikh@gmail.com"
          git config --global user.name "Dmitry Krutskikh"
          git checkout master
          git push -u bitbucket master
