import 'package:dart_code_metrics/src/analyzers/lint_analyzer/models/severity.dart';
import 'package:dart_code_metrics/src/analyzers/lint_analyzer/rules/rules_list/prefer_first/prefer_first.dart';
import 'package:test/test.dart';

import '../../../../../helpers/rule_test_helper.dart';

const _examplePath = 'prefer_first/examples/example.dart';

void main() {
  group(
    'PreferFirstRule',
    () {
      test('initialization', () async {
        final unit = await RuleTestHelper.resolveFromFile(_examplePath);
        final issues = PreferFirstRule().check(unit);

        RuleTestHelper.verifyInitialization(
          issues: issues,
          ruleId: 'prefer-first',
          severity: Severity.style,
        );
      });

      test('reports about found issues', () async {
        final unit = await RuleTestHelper.resolveFromFile(_examplePath);
        final issues = PreferFirstRule().check(unit);

        RuleTestHelper.verifyIssues(
          issues: issues,
          startOffsets: [
            267,
            390,
            604,
            661,
            799,
            855,
            1054,
            1157,
            1450,
            1609,
            1846,
            1965,
            2232,
            2375,
            2622,
            2749,
            2976,
            3087,
            3349,
            3488,
            3799,
            3888,
            4128,
            4184,
            4479,
            4646,
          ],
          startLines: [
            11,
            16,
            24,
            25,
            31,
            34,
            42,
            47,
            56,
            61,
            69,
            74,
            82,
            87,
            95,
            100,
            108,
            113,
            121,
            126,
            135,
            136,
            143,
            146,
            155,
            160,
          ],
          startColumns: [
            34,
            5,
            31,
            31,
            5,
            5,
            29,
            5,
            7,
            5,
            33,
            5,
            39,
            5,
            35,
            5,
            31,
            5,
            38,
            5,
            7,
            47,
            5,
            5,
            7,
            5,
          ],
          endOffsets: [
            288,
            404,
            621,
            668,
            813,
            860,
            1070,
            1171,
            1480,
            1623,
            1866,
            1979,
            2258,
            2389,
            2644,
            2763,
            2994,
            3101,
            3374,
            3502,
            3832,
            3911,
            4142,
            4189,
            4511,
            4660,
          ],
          messages: [
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
            'Use first instead of access to element at zero index.',
          ],
          replacementComments: [
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
            "Replace with 'first'.",
          ],
          replacements: [
            'iterable.first',
            '..first',
            'list.first',
            'list.first',
            '..first',
            '..first',
            'set.first',
            '..first',
            'doubleLinkedQueue.first',
            '..first',
            'hashSet.first',
            '..first',
            'linkedHashSet.first',
            '..first',
            'listQueue.first',
            '..first',
            'queue.first',
            '..first',
            'splayTreeSet.first',
            '..first',
            'unmodifiableListView.first',
            'unmodifiableListView.first',
            '..first',
            '..first',
            'unmodifiableSetView.first',
            '..first',
          ],
          locationTexts: [
            'iterable.elementAt(0)',
            '..elementAt(0)',
            'list.elementAt(0)',
            'list[0]',
            '..elementAt(0)',
            '..[0]',
            'set.elementAt(0)',
            '..elementAt(0)',
            'doubleLinkedQueue.elementAt(0)',
            '..elementAt(0)',
            'hashSet.elementAt(0)',
            '..elementAt(0)',
            'linkedHashSet.elementAt(0)',
            '..elementAt(0)',
            'listQueue.elementAt(0)',
            '..elementAt(0)',
            'queue.elementAt(0)',
            '..elementAt(0)',
            'splayTreeSet.elementAt(0)',
            '..elementAt(0)',
            'unmodifiableListView.elementAt(0)',
            'unmodifiableListView[0]',
            '..elementAt(0)',
            '..[0]',
            'unmodifiableSetView.elementAt(0)',
            '..elementAt(0)',
          ],
        );
      });
    },
  );
}
