name: dart_code_metrics
description: |
  Command line tool which helps to improve code quality.
  Reports cyclomatic complexity and method length in plain console, JSON, HTML and Codeclimate formats
version: 1.4.0
homepage: https://github.com/wrike/dart-code-metrics

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  analyzer: '>=0.38.0 <0.40.0'
  ansicolor: ^1.0.0
  args: ^1.5.0
  crypto: ^2.1.0
  glob: ^1.2.0
  html: '>=0.13.0 < 1.0.0'
  meta: ^1.1.0
  path: ^1.6.0
  quiver: ^2.1.0
  resource: ^2.1.0

dev_dependencies:
  coverage: ^0.13.5
  coveralls: ^5.4.0
  dependency_validator: ^1.5.0
  lcov: ^5.4.0
  mockito: ^4.1.0
  pedantic: ^1.9.0
  test: ^1.13.0

executables:
  metrics:
